import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "sonner";
import "./global.css";
import "@/styles/global.scss";
import Footer from "@/components/web/Footer/Footer";
import MiniNav from "@/components/web/Nav/MiniNav";
import PrimaryNav from "@/components/web/Nav/PrimaryNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "BBR Web",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider>
          <MiniNav />
          <PrimaryNav />
          {children}
          <Toaster position="top-center" visibleToasts={9} richColors closeButton theme="dark" />
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
